version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html/:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    build: ./php
    volumes:
      - /var/www/html/:/var/www/html

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
