---
- name: Deploy Dockerized Web Application
  hosts: all
  become: yes
  roles:
    - docker
    - nginx

    #Роли отключены, т.к. окружение настраивается в Dockerfile
    # - php 
    # - mysql
